name: Prisma Push Prod

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    env:
      TRAK_DB_URL: ${{secrets.PROD_TRAK_DB_URL}}

    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@master
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Installing dependencies
        uses: borales/actions-yarn@master
        with:
          cmd: install
      - name: Push prisma changes
        uses: borales/actions-yarn@master
        with:
          cmd: push

